version: "3.8"

services:
  dev:
    container_name: benchmark_postgres
    build:
      context: .
    env_file:
      - .env
    command: CGO_ENABLED=0 go build -trimpath -o main main.go
    depends_on:
      - pgadmin
      - postgres

  postgres:
    image: postgres:10.4
    env_file:
      - .env
    ports:
      - 35000:${POSTGRES_PORT}

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"  